import {
  defineConfig,
  presetAttributify,
  presetWind4,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  dark: 'class',
  presets: [
    presetWind4(),
    presetAttributify(),
  ],
  theme: {
    colors: {
      'box': 'var(--default-box-color)',
      'theme': 'var(--theme-color)',
      'hover-color': 'var(--art-hover-color)',
      'active-color': 'var(--art-active-color)',
      'el-active-color': 'var(--art-active-color)',
      'primary': 'var(--art-primary)',
      'secondary': 'var(--art-secondary)',
      'error': 'var(--art-error)',
      'info': 'var(--art-info)',
      'success': 'var(--art-success)',
      'warning': 'var(--art-warning)',
      'danger': 'var(--art-danger)',
      'g': {
        100: 'var(--art-gray-100)',
        200: 'var(--art-gray-200)',
        300: 'var(--art-gray-300)',
        400: 'var(--art-gray-400)',
        500: 'var(--art-gray-500)',
        600: 'var(--art-gray-600)',
        700: 'var(--art-gray-700)',
        800: 'var(--art-gray-800)',
        900: 'var(--art-gray-900)',
      },
    },
  },
  shortcuts: {
    'flex-c': 'flex items-center',
    'flex-b': 'flex justify-between',
    'flex-cc': 'flex items-center justify-center',
    'flex-cb': 'flex items-center justify-between',
    'tad-200': 'transition-all duration-200',
    'tad-300': 'transition-all duration-300',
    'border-full-d': 'border border-[var(--default-border)]',
    'border-b-d': 'border-b border-[var(--default-border)]',
    'border-t-d': 'border-t border-[var(--default-border)]',
    'border-l-d': 'border-l border-[var(--default-border)]',
    'border-r-d': 'border-r border-[var(--default-border)]',
    'c-p': 'cursor-pointer',
  },
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
